figure 10 plot lineages
meyer-lab/tHMM pull request #573
Opened 2020-09-08 16:00 UTC by Farnazmdi

2020-09-09 19:54 UTC, aarmey requested changes
They all seem to be black?

2020-09-09 19:56 UTC, Farnazmdi commented
Yes sorry, just realized. I’m working on it in my local.

2020-09-10 01:17 UTC, Farnazmdi commented
![image](https://user-images.githubusercontent.com/34812750/92670340-adb62d80-f2c8-11ea-8467-fb70393a7b70.png)
@aarmey it builds now.

2020-09-10 03:31 UTC, aarmey approved these changes
Great. One change and then we can merge this.

I'm surprised the states don't look all that different. We can look at the fit emissions parameters to see what distinguishes them... maybe it's something cell cycle-specific.

2020-09-10 03:31 UTC, aarmey commented on lineage/figures/figure10.py
> +    i = 0
This looks a lot like a loop to me...

2020-09-10 06:24 UTC, merged