Resubm
meyer-lab/tHMM pull request #860
Opened 2021-11-03 20:36 UTC by Farnazmdi

2021-11-03 20:58 UTC, aarmey requested changes

2021-11-03 20:58 UTC, aarmey commented on lineage/Analyze.py
> +    results_dict["accuracy_before_switching"] = 100 * np.mean(ravel_true_states == pred_states_by_lineage)
Do you need this anymore?

2021-11-03 20:58 UTC, aarmey commented on lineage/Analyze.py
> +        results_dict[str("log_score"+str(ii))] = np.sum(tHMMobj.log_score(sw_states, pi=pi_arg, T=T_arg, E=E_arg))
Do you need this anymore?

2021-11-03 20:58 UTC, aarmey commented on lineage/figures/figure6.py
> +    list_of_populations = []
The abundance of the cell states should be changed by adjusting pi and T, not by filtering out lineages.

2021-11-03 20:58 UTC, aarmey commented on lineage/figures/figure6.py
> +    wass, _, dict_out, _ = commonAnalyze(list_of_populations, 2, xtype="wass", list_of_fpi=[pi] * 2*num_data_points, list_of_fT=[T] * 2*num_data_points, parallel=True)
Why do you have to do this?

2021-11-06 00:31 UTC, Farnazmdi commented
I edited this branch so it only includes some edits to figure S17.

2021-11-06 01:50 UTC, aarmey approved these changes
Great!

2021-11-06 01:50 UTC, merged