fonts for letters and some other stuf
meyer-lab/tHMM pull request #864
Opened 2021-11-12 23:03 UTC by Farnazmdi

2021-11-13 02:37 UTC, aarmey requested changes
Just saw one tiny edit. Did you mean to commit the figure?

2021-11-13 02:37 UTC, aarmey commented on lineage/figures/figureCommon.py
> +        ax[i].set_title(r"Error in estimating T")
Look at capitalization here.

2021-11-15 02:33 UTC, Farnazmdi commented
Yes, because of the color of states in the cartoon.

2021-11-15 13:39 UTC, aarmey commented
Merging!

2021-11-15 13:39 UTC, merged